Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  # Para configurar la disponibilidad de puertos para ingresar al server
  config.vm.network "forwarded_port", guest: 80, host: 8080                                     # Permite acceso público desde cualquier máquina
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"             Network configuration to disable public access

  # Para crear una red privada que permita unicamente conexión host-only con la vm
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Establecer una carpeta compartida entre el repositorio y la maquina virtual
  # El primer argumento es la carpeta en el repo, el segundo argumento es la carpeta
  # dentro de la maquina virtual
  config.vm.synced_folder "../sharedVM", "~/"

  # Para provisionar la maquina virtual
  config.vm.provider "virtualbox" do |vb|
    # Habilitar la interfaz grafica
    vb.gui = true
    # Establecer la RAM:
    vb.memory = "3072"
  end

  # Permitir el provisionamiento a través de código shell (bash)

  # Script shell que permite desactivar el firewall, en caso de que este nos cause problemas
  #   config.vm.provision "shell", inline: <<-SHELL
  #     sudo systemctl stop firewalld
  #     sudo systemctl disable firewalld
  #   SHELL

  config.vm.provision :shell, path: "apacheServer.sh"

end
